version: '3'

services:
    app:
        image: main-sample-php:latest
        container_name: php-sample-main
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        # command: npm start
        networks:
            - store
        tty: true

    service-server:
        image: server-sample-php:latest
        container_name: php-sample-server
        build:
            context: ./server/
            dockerfile: Dockerfile
        ports:
            - "3001:80"
        # command: npm start
        networks:
            - store
        tty: true

networks:
    store:
        name: sample-php-network
        external: true